/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

/**
 *
 * @author RashedGtz
 */
public class AccountOption extends javax.swing.JFrame {

    /**
     * Creates new form AccountOption
     */
    public AccountOption() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SignInBut = new javax.swing.JButton();
        SignUpBut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 360));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(640, 360));

        jPanel1.setLayout(null);

        SignInBut.setBackground(new java.awt.Color(153, 153, 255));
        SignInBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SignInBut.png"))); // NOI18N
        SignInBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInButMouseClicked(evt);
            }
        });
        jPanel1.add(SignInBut);
        SignInBut.setBounds(220, 240, 210, 60);

        SignUpBut.setBackground(new java.awt.Color(153, 153, 255));
        SignUpBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SignUpBut.png"))); // NOI18N
        SignUpBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButMouseClicked(evt);
            }
        });
        jPanel1.add(SignUpBut);
        SignUpBut.setBounds(220, 150, 210, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/GRRS.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 20, 80, 60);

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TECHNOLOGY");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 80, 170, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screen.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButMouseClicked
        new CreateNewSeller().setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_SignUpButMouseClicked

    private void SignInButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButMouseClicked
        new Login().setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_SignInButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SignInBut;
    private javax.swing.JButton SignUpBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
