/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import javax.swing.JOptionPane;

/**
 *
 * @author RashedGtz
 */
public class AdminConsol extends javax.swing.JFrame {

    /**
     * Creates new form AdminConsol
     */
    public AdminConsol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseIcon = new javax.swing.JLabel();
        TransactionBut = new javax.swing.JButton();
        PendingBut = new javax.swing.JButton();
        UpdateAdmin = new javax.swing.JButton();
        ManageProduct = new javax.swing.JButton();
        ManageSeller = new javax.swing.JButton();
        ManageCategory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 600));
        jPanel1.setLayout(null);

        CloseIcon.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CloseIcon.setForeground(new java.awt.Color(255, 255, 255));
        CloseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseIconMouseClicked(evt);
            }
        });
        jPanel1.add(CloseIcon);
        CloseIcon.setBounds(1070, 0, 25, 30);

        TransactionBut.setBackground(new java.awt.Color(153, 153, 255));
        TransactionBut.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TransactionBut.setForeground(new java.awt.Color(255, 255, 255));
        TransactionBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/TransactionBut.png"))); // NOI18N
        TransactionBut.setBorderPainted(false);
        TransactionBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionButMouseClicked(evt);
            }
        });
        jPanel1.add(TransactionBut);
        TransactionBut.setBounds(770, 160, 220, 160);

        PendingBut.setBackground(new java.awt.Color(153, 153, 255));
        PendingBut.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PendingBut.setForeground(new java.awt.Color(255, 255, 255));
        PendingBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PendingBut.png"))); // NOI18N
        PendingBut.setBorderPainted(false);
        PendingBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingButMouseClicked(evt);
            }
        });
        PendingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButActionPerformed(evt);
            }
        });
        jPanel1.add(PendingBut);
        PendingBut.setBounds(770, 380, 200, 160);

        UpdateAdmin.setBackground(new java.awt.Color(153, 153, 255));
        UpdateAdmin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        UpdateAdmin.setForeground(new java.awt.Color(255, 255, 255));
        UpdateAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UpdateAdminBut.png"))); // NOI18N
        UpdateAdmin.setBorderPainted(false);
        UpdateAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateAdminMouseClicked(evt);
            }
        });
        UpdateAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAdminActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateAdmin);
        UpdateAdmin.setBounds(460, 380, 220, 160);

        ManageProduct.setBackground(new java.awt.Color(153, 153, 255));
        ManageProduct.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ManageProduct.setForeground(new java.awt.Color(255, 255, 255));
        ManageProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ProductBut.png"))); // NOI18N
        ManageProduct.setBorderPainted(false);
        ManageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageProductMouseClicked(evt);
            }
        });
        jPanel1.add(ManageProduct);
        ManageProduct.setBounds(140, 380, 220, 160);

        ManageSeller.setBackground(new java.awt.Color(153, 153, 255));
        ManageSeller.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ManageSeller.setForeground(new java.awt.Color(255, 255, 255));
        ManageSeller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SellerBut.png"))); // NOI18N
        ManageSeller.setBorderPainted(false);
        ManageSeller.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageSellerMouseClicked(evt);
            }
        });
        ManageSeller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageSellerActionPerformed(evt);
            }
        });
        jPanel1.add(ManageSeller);
        ManageSeller.setBounds(140, 160, 220, 160);

        ManageCategory.setBackground(new java.awt.Color(153, 153, 255));
        ManageCategory.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ManageCategory.setForeground(new java.awt.Color(255, 255, 255));
        ManageCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CategoryBut.png"))); // NOI18N
        ManageCategory.setBorderPainted(false);
        ManageCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageCategoryMouseClicked(evt);
            }
        });
        jPanel1.add(ManageCategory);
        ManageCategory.setBounds(460, 160, 220, 160);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("ADMIN CONSOL");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(480, 30, 197, 60);

        LogOut.setBackground(new java.awt.Color(153, 153, 255));
        LogOut.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoutBut2.png"))); // NOI18N
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut);
        LogOut.setBounds(940, 70, 150, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackGround(11-6).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseIconMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_CloseIconMouseClicked

    private void ManageSellerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageSellerMouseClicked
        new SellerBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageSellerMouseClicked

    private void ManageCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageCategoryMouseClicked
        new CategoryBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageCategoryMouseClicked

    private void ManageProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProductMouseClicked
        new ProductBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ManageProductMouseClicked

    private void UpdateAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateAdminMouseClicked
        new UpdateAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UpdateAdminMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_LogOutMouseClicked

    private void ManageSellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageSellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManageSellerActionPerformed

    private void TransactionButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionButMouseClicked
        new Transaction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransactionButMouseClicked

    private void PendingButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingButMouseClicked
        new Pending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PendingButMouseClicked

    private void PendingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButActionPerformed

    private void UpdateAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateAdminActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminConsol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseIcon;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton ManageCategory;
    private javax.swing.JButton ManageProduct;
    private javax.swing.JButton ManageSeller;
    private javax.swing.JButton PendingBut;
    private javax.swing.JButton TransactionBut;
    private javax.swing.JButton UpdateAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
