/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RashedGtz
 */
public class CategoryBG extends javax.swing.JFrame {

    /**
     * Creates new form CategoryBG
     */
    public CategoryBG() {
        initComponents();
        SelectCategory();
    }

    String url = "jdbc:mysql://localhost:3306/ShopManagement";
    String uname = "root";
    String pass = "239515amimysql";

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    public void SelectCategory() {
        try {
            con = DriverManager.getConnection(url, uname, pass);
            st = con.createStatement();
            rs = st.executeQuery("Select * from shopmanagement.categorytable");
            CatTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProductBut = new javax.swing.JButton();
        SellerBut = new javax.swing.JButton();
        HomeBut = new javax.swing.JButton();
        CategoryBut = new javax.swing.JButton();
        TransactionBut = new javax.swing.JButton();
        PendingBut = new javax.swing.JButton();
        CloseBut = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CatTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        CatId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CatName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AddBut = new javax.swing.JButton();
        EditBut = new javax.swing.JButton();
        DeleteBut = new javax.swing.JButton();
        ClearBut = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 600));
        jPanel1.setLayout(null);

        ProductBut.setBackground(new java.awt.Color(153, 153, 255));
        ProductBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ProductBut.setForeground(new java.awt.Color(255, 255, 255));
        ProductBut.setText("PRODUCT");
        ProductBut.setBorder(null);
        ProductBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButMouseClicked(evt);
            }
        });
        ProductBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductButActionPerformed(evt);
            }
        });
        jPanel1.add(ProductBut);
        ProductBut.setBounds(230, 70, 171, 40);

        SellerBut.setBackground(new java.awt.Color(153, 153, 255));
        SellerBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SellerBut.setForeground(new java.awt.Color(255, 255, 255));
        SellerBut.setText("SELLER");
        SellerBut.setBorder(null);
        SellerBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerButMouseClicked(evt);
            }
        });
        jPanel1.add(SellerBut);
        SellerBut.setBounds(60, 70, 171, 40);

        HomeBut.setBackground(new java.awt.Color(153, 153, 255));
        HomeBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        HomeBut.setIcon(new javax.swing.ImageIcon("D:\\Icon\\25h\\HOME_BUT.png")); // NOI18N
        HomeBut.setBorder(null);
        HomeBut.setBorderPainted(false);
        HomeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButMouseClicked(evt);
            }
        });
        HomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBut);
        HomeBut.setBounds(10, 70, 50, 40);

        CategoryBut.setBackground(new java.awt.Color(102, 102, 255));
        CategoryBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        CategoryBut.setForeground(new java.awt.Color(255, 255, 255));
        CategoryBut.setText("CATEGORY");
        CategoryBut.setBorder(null);
        CategoryBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryButMouseClicked(evt);
            }
        });
        jPanel1.add(CategoryBut);
        CategoryBut.setBounds(400, 70, 171, 40);

        TransactionBut.setBackground(new java.awt.Color(153, 153, 255));
        TransactionBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        TransactionBut.setForeground(new java.awt.Color(255, 255, 255));
        TransactionBut.setText("TRANSACTION");
        TransactionBut.setBorder(null);
        TransactionBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionButMouseClicked(evt);
            }
        });
        jPanel1.add(TransactionBut);
        TransactionBut.setBounds(570, 70, 171, 40);

        PendingBut.setBackground(new java.awt.Color(153, 153, 255));
        PendingBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        PendingBut.setForeground(new java.awt.Color(255, 255, 255));
        PendingBut.setText("PENDING");
        PendingBut.setBorder(null);
        PendingBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingButMouseClicked(evt);
            }
        });
        PendingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButActionPerformed(evt);
            }
        });
        jPanel1.add(PendingBut);
        PendingBut.setBounds(740, 70, 171, 40);

        CloseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
        });
        jPanel1.add(CloseBut);
        CloseBut.setBounds(1070, 0, 25, 30);

        CatTable.setBackground(new java.awt.Color(255, 255, 255));
        CatTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CatTable.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        CatTable.setForeground(new java.awt.Color(153, 153, 153));
        CatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Category ID", "Name"
            }
        ));
        CatTable.setGridColor(new java.awt.Color(204, 204, 204));
        CatTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        CatTable.setRowHeight(25);
        CatTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        CatTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        CatTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        CatTable.setShowGrid(true);
        CatTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CatTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CatTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 180, 1020, 200);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("CATEGORY MANAGER");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 130, 290, 35);

        CatId.setBackground(new java.awt.Color(204, 255, 255));
        CatId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CatId.setForeground(new java.awt.Color(51, 153, 255));
        CatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatIdActionPerformed(evt);
            }
        });
        jPanel1.add(CatId);
        CatId.setBounds(200, 450, 280, 40);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Category ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(81, 460, 100, 22);

        CatName.setBackground(new java.awt.Color(204, 255, 255));
        CatName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CatName.setForeground(new java.awt.Color(51, 153, 255));
        CatName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatNameActionPerformed(evt);
            }
        });
        jPanel1.add(CatName);
        CatName.setBounds(660, 450, 280, 40);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 460, 60, 22);

        AddBut.setBackground(new java.awt.Color(153, 153, 255));
        AddBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AddBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ADD_But.png"))); // NOI18N
        AddBut.setBorder(null);
        AddBut.setBorderPainted(false);
        AddBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButMouseClicked(evt);
            }
        });
        jPanel1.add(AddBut);
        AddBut.setBounds(100, 530, 140, 40);

        EditBut.setBackground(new java.awt.Color(153, 153, 255));
        EditBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EditBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit_But.png"))); // NOI18N
        EditBut.setBorder(null);
        EditBut.setBorderPainted(false);
        EditBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButMouseClicked(evt);
            }
        });
        jPanel1.add(EditBut);
        EditBut.setBounds(360, 530, 140, 40);

        DeleteBut.setBackground(new java.awt.Color(153, 153, 255));
        DeleteBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DeleteBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dlelete_But.png"))); // NOI18N
        DeleteBut.setBorder(null);
        DeleteBut.setBorderPainted(false);
        DeleteBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButMouseClicked(evt);
            }
        });
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBut);
        DeleteBut.setBounds(620, 530, 140, 40);

        ClearBut.setBackground(new java.awt.Color(153, 153, 255));
        ClearBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ClearBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Clear_1.png"))); // NOI18N
        ClearBut.setBorder(null);
        ClearBut.setBorderPainted(false);
        ClearBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButMouseClicked(evt);
            }
        });
        jPanel1.add(ClearBut);
        ClearBut.setBounds(860, 530, 140, 40);

        LogOut.setBackground(new java.awt.Color(153, 153, 255));
        LogOut.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoutBut2.png"))); // NOI18N
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut);
        LogOut.setBounds(910, 70, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackGround(11-6).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButMouseClicked
        new AdminConsol().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButMouseClicked

    private void HomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButActionPerformed

    private void PendingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButActionPerformed

    private void CatTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CatTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) CatTable.getModel();
        int Myindex = CatTable.getSelectedRow();
        CatId.setText(model.getValueAt(Myindex, 0).toString());
        CatName.setText(model.getValueAt(Myindex, 1).toString());
    }//GEN-LAST:event_CatTableMouseClicked

    private void CatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatIdActionPerformed

    private void CatNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatNameActionPerformed

    private void AddButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButMouseClicked

        int chk = 0;
        int UniqueChk = 0;
        int value = 10;
        int value2 = 10;
        String CategoryId = "";
        String Category_Name = "";

        if (CatId.getText().isEmpty() || CatName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information missing");
        } else {
            chk = 1;
            CategoryId = CatId.getText();
            Category_Name = CatName.getText();
        }

        if (chk == 1) {

            try {
                con = DriverManager.getConnection(url, uname, pass);

                String Query = "select count(*) from categorytable where CatId = " + CategoryId;
                Statement Add = con.createStatement();
                ResultSet Rs = Add.executeQuery(Query);
                Rs.next();

                value = Rs.getInt("count(*)");
//                    System.out.println(value);
                Add.close();
                con.close();

            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
                con = DriverManager.getConnection(url, uname, pass);

                String Query = "select count(*) from categorytable where CatName = '" + Category_Name + "'";
                Statement Add = con.createStatement();
                ResultSet Rs = Add.executeQuery(Query);
                Rs.next();

                value2 = Rs.getInt("count(*)");
//                    System.out.println(value);
                Add.close();
                con.close();

            } catch (Exception e) {
                e.printStackTrace();
            }

            if (value > 0 || value2 > 0) {
                JOptionPane.showMessageDialog(this, "Category Id or Category Name already existed");
            } else {
                UniqueChk = 1;
            }

        }

        if (UniqueChk == 1) {
            try {
                con = DriverManager.getConnection(url, uname, pass);
                PreparedStatement add = con.prepareStatement("insert into categorytable values(?,?)");
                add.setInt(1, Integer.valueOf(CatId.getText()));
                add.setString(2, CatName.getText());
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Category Added Success");
                con.close();
                SelectCategory();
            } catch (Exception e) {
                e.printStackTrace();
            }

            CatId.setText("");
            CatName.setText("");
        }

    }//GEN-LAST:event_AddButMouseClicked

    private void EditButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButMouseClicked
        if (CatId.getText().isEmpty() || CatName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information Missing");
        } else {
            try {
                con = DriverManager.getConnection(url, uname, pass);

                String E_CatId = CatId.getText();
                String E_CatName = CatName.getText();

                String Query = "Update shopmanagement.categorytable set CatName='" + E_CatName + "'" + "where CatId=" + E_CatId;
                Statement Add = con.createStatement();
                Add.executeUpdate(Query);
                con.close();
                SelectCategory();
                JOptionPane.showMessageDialog(this, "Category Information Edited Successfully");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_EditButMouseClicked

    private void DeleteButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButMouseClicked
        if (CatId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter Seller Information");
        } else {
            int response = JOptionPane.showConfirmDialog(this, "Do you want to delete this category ? All the products of this category will also be deleted ", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.YES_OPTION) {
                try {
                    con = DriverManager.getConnection(url, uname, pass);
                    String Del_CatId = CatId.getText();
                    String Query = "Delete from shopmanagement.categorytable where CatId=" + Del_CatId;
                    Statement Add = con.createStatement();
                    Add.executeUpdate(Query);
                    con.close();
                    SelectCategory();
                } catch (Exception e) {
                    e.printStackTrace();
                }

                try {
                    con = DriverManager.getConnection(url, uname, pass);
                    String Del_CatName = CatName.getText();
                    String Query = "Delete from shopmanagement.producttable where Category = '" + Del_CatName + "'";
                    Statement Add = con.createStatement();
                    Add.executeUpdate(Query);
                    con.close();
                    SelectCategory();
                    JOptionPane.showMessageDialog(this, "Category Deleted Successfully");
                } catch (Exception e) {
                    e.printStackTrace();
                }
                CatId.setText("");
                CatName.setText("");
            } else {
                CatId.setText("");
                CatName.setText("");
            }

        }
    }//GEN-LAST:event_DeleteButMouseClicked

    private void ClearButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButMouseClicked
        CatId.setText("");
        CatName.setText("");
    }//GEN-LAST:event_ClearButMouseClicked

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButActionPerformed

    private void ProductButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductButActionPerformed

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_CloseButMouseClicked

    private void SellerButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerButMouseClicked
        new SellerBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellerButMouseClicked

    private void ProductButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButMouseClicked
        new ProductBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductButMouseClicked

    private void TransactionButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionButMouseClicked
        new Transaction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransactionButMouseClicked

    private void PendingButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingButMouseClicked
        new Pending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PendingButMouseClicked

    private void CategoryButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryButMouseClicked
        new CategoryBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryBG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JTextField CatId;
    private javax.swing.JTextField CatName;
    private javax.swing.JTable CatTable;
    private javax.swing.JButton CategoryBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JLabel CloseBut;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JButton EditBut;
    private javax.swing.JButton HomeBut;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton PendingBut;
    private javax.swing.JButton ProductBut;
    private javax.swing.JButton SellerBut;
    private javax.swing.JButton TransactionBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
