/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RashedGtz
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    String url = "jdbc:mysql://localhost:3306/ShopManagement";
    String uname = "root";
    String pass = "239515amimysql";
    static String SellerNameAccepted="";

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        AccountType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        Pass = new javax.swing.JPasswordField();
        CloseIcon1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        ShowPassword = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 360));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(640, 360));
        jPanel2.setMinimumSize(new java.awt.Dimension(640, 360));
        jPanel2.setPreferredSize(new java.awt.Dimension(640, 360));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("SIGN IN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(380, 20, 89, 32);

        UserName.setBackground(new java.awt.Color(255, 255, 255));
        UserName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(51, 153, 255));
        jPanel2.add(UserName);
        UserName.setBounds(350, 140, 237, 37);

        AccountType.setBackground(new java.awt.Color(51, 153, 255));
        AccountType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AccountType.setForeground(new java.awt.Color(255, 255, 255));
        AccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Seller" }));
        AccountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountTypeActionPerformed(evt);
            }
        });
        jPanel2.add(AccountType);
        AccountType.setBounds(351, 89, 237, 37);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("User Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(250, 150, 86, 18);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(250, 200, 86, 18);

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Type");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(247, 100, 86, 18);

        Clear.setBackground(new java.awt.Color(153, 153, 255));
        Clear.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Clear_1.png"))); // NOI18N
        Clear.setBorder(null);
        Clear.setBorderPainted(false);
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });
        jPanel2.add(Clear);
        Clear.setBounds(470, 290, 150, 40);

        LogIn.setBackground(new java.awt.Color(153, 153, 255));
        LogIn.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogInBut.png"))); // NOI18N
        LogIn.setBorder(null);
        LogIn.setBorderPainted(false);
        LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogInMouseClicked(evt);
            }
        });
        jPanel2.add(LogIn);
        LogIn.setBounds(250, 290, 150, 40);

        Pass.setBackground(new java.awt.Color(255, 255, 255));
        Pass.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(0, 0, 0));
        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        jPanel2.add(Pass);
        Pass.setBounds(350, 190, 237, 37);

        CloseIcon1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CloseIcon1.setForeground(new java.awt.Color(255, 255, 255));
        CloseIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseIcon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseIcon1MouseClicked(evt);
            }
        });
        jPanel2.add(CloseIcon1);
        CloseIcon1.setBounds(610, 0, 25, 30);

        Back.setBackground(new java.awt.Color(153, 153, 255));
        Back.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 204, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackBut.png"))); // NOI18N
        Back.setBorder(null);
        Back.setBorderPainted(false);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back);
        Back.setBounds(10, 10, 42, 26);

        ShowPassword.setText("Show Password");
        ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPasswordMouseClicked(evt);
            }
        });
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(ShowPassword);
        ShowPassword.setBounds(350, 240, 140, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogIn.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AccountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountTypeActionPerformed

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        UserName.setText("");
        Pass.setText("");
    }//GEN-LAST:event_ClearMouseClicked

    private void LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogInMouseClicked
        String Type = AccountType.getSelectedItem().toString();

        if ( Type.equals("Seller") ) {
            String Query = "Select * from shopmanagement.sellerinfo where UserName = '" + UserName.getText() + "' and Password ='" + Pass.getText() + "'";

            try {
                con = DriverManager.getConnection(url, uname, pass);
                st = con.createStatement();
                rs = st.executeQuery(Query);
                if (rs.next()) {
                    SellerNameAccepted = UserName.getText();
                    new SellerConsol().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Seller Id or Password");
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        else if( Type.equals("Admin") )
        {
            String Query = "Select * from shopmanagement.admintable where AdminName = '" + UserName.getText() + "' and AdminPass ='" + Pass.getText() + "'";

            try {
                con = DriverManager.getConnection(url, uname, pass);
                st = con.createStatement();
                rs = st.executeQuery(Query);
                if (rs.next()) {
                    new AdminConsol().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Admin Id or Password");
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }


    }//GEN-LAST:event_LogInMouseClicked

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void CloseIcon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseIcon1MouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if( response == JOptionPane.YES_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_CloseIcon1MouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        new AccountOption().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    private void ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordMouseClicked
  
    }//GEN-LAST:event_ShowPasswordMouseClicked

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        if(ShowPassword.isSelected())
        {
            Pass.setEchoChar((char)0);
        }
        else
        {
            Pass.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccountType;
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel CloseIcon1;
    private javax.swing.JButton LogIn;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
