/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RashedGtz
 */
public class ProductBG extends javax.swing.JFrame {

    /**
     * Creates new form ProductBG
     */
    public ProductBG() {
        initComponents();
        SelectProduct();
        GetCategory();
    }

    String url = "jdbc:mysql://localhost:3306/ShopManagement";
    String uname = "root";
    String pass = "239515amimysql";

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    public void SelectProduct() {
        try {
            con = DriverManager.getConnection(url, uname, pass);
            st = con.createStatement();
            rs = st.executeQuery("Select * from shopmanagement.producttable");
            ProductTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Getting all the Category Name from Category Table set to Category Combo Box 
    public void GetCategory() {
        try {
            con = DriverManager.getConnection(url, uname, pass);
            st = con.createStatement();
            String Query = "Select * from shopmanagement.categorytable";

            rs = st.executeQuery(Query);

            while (rs.next()) {
                String MyCategory = rs.getString("CatName");
                Category.addItem(MyCategory);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProductBut = new javax.swing.JButton();
        SellerBut = new javax.swing.JButton();
        HomeBut = new javax.swing.JButton();
        CategoryBut = new javax.swing.JButton();
        TransactionBut = new javax.swing.JButton();
        PendingBut = new javax.swing.JButton();
        CloseBut = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Category = new javax.swing.JComboBox<>();
        ProductId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PPU = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ProductName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AddBut = new javax.swing.JButton();
        EditBut = new javax.swing.JButton();
        DeleteBut = new javax.swing.JButton();
        ClearBut = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        ProductBut.setBackground(new java.awt.Color(102, 102, 255));
        ProductBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ProductBut.setForeground(new java.awt.Color(255, 255, 255));
        ProductBut.setText("PRODUCT");
        ProductBut.setBorder(null);
        ProductBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButMouseClicked(evt);
            }
        });
        jPanel1.add(ProductBut);
        ProductBut.setBounds(230, 70, 171, 40);

        SellerBut.setBackground(new java.awt.Color(153, 153, 255));
        SellerBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SellerBut.setForeground(new java.awt.Color(255, 255, 255));
        SellerBut.setText("SELLER");
        SellerBut.setBorder(null);
        SellerBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerButMouseClicked(evt);
            }
        });
        jPanel1.add(SellerBut);
        SellerBut.setBounds(60, 70, 171, 40);

        HomeBut.setBackground(new java.awt.Color(153, 153, 255));
        HomeBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        HomeBut.setIcon(new javax.swing.ImageIcon("D:\\Icon\\25h\\HOME_BUT.png")); // NOI18N
        HomeBut.setBorder(null);
        HomeBut.setBorderPainted(false);
        HomeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButMouseClicked(evt);
            }
        });
        HomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBut);
        HomeBut.setBounds(10, 70, 50, 40);

        CategoryBut.setBackground(new java.awt.Color(153, 153, 255));
        CategoryBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        CategoryBut.setForeground(new java.awt.Color(255, 255, 255));
        CategoryBut.setText("CATEGORY");
        CategoryBut.setBorder(null);
        CategoryBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryButMouseClicked(evt);
            }
        });
        jPanel1.add(CategoryBut);
        CategoryBut.setBounds(400, 70, 171, 40);

        TransactionBut.setBackground(new java.awt.Color(153, 153, 255));
        TransactionBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        TransactionBut.setForeground(new java.awt.Color(255, 255, 255));
        TransactionBut.setText("TRANSACTION");
        TransactionBut.setBorder(null);
        TransactionBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionButMouseClicked(evt);
            }
        });
        jPanel1.add(TransactionBut);
        TransactionBut.setBounds(570, 70, 171, 40);

        PendingBut.setBackground(new java.awt.Color(153, 153, 255));
        PendingBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        PendingBut.setForeground(new java.awt.Color(255, 255, 255));
        PendingBut.setText("PENDING");
        PendingBut.setBorder(null);
        PendingBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingButMouseClicked(evt);
            }
        });
        PendingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButActionPerformed(evt);
            }
        });
        jPanel1.add(PendingBut);
        PendingBut.setBounds(740, 70, 171, 40);

        CloseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
        });
        jPanel1.add(CloseBut);
        CloseBut.setBounds(1070, 0, 25, 30);

        ProductTable.setBackground(new java.awt.Color(255, 255, 255));
        ProductTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductTable.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        ProductTable.setForeground(new java.awt.Color(153, 153, 153));
        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Price Per Unit", "Quantity", "Category"
            }
        ));
        ProductTable.setGridColor(new java.awt.Color(204, 204, 204));
        ProductTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        ProductTable.setRowHeight(25);
        ProductTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        ProductTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ProductTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ProductTable.setShowGrid(true);
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ProductTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 180, 1060, 160);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("MANAGE PRODUCTS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 130, 270, 35);

        jLabel9.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("Category");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 370, 90, 22);

        Category.setBackground(new java.awt.Color(51, 153, 255));
        Category.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Category.setForeground(new java.awt.Color(255, 255, 255));
        Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryActionPerformed(evt);
            }
        });
        jPanel1.add(Category);
        Category.setBounds(160, 360, 310, 40);

        ProductId.setBackground(new java.awt.Color(204, 255, 255));
        ProductId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ProductId.setForeground(new java.awt.Color(51, 153, 255));
        ProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductIdActionPerformed(evt);
            }
        });
        jPanel1.add(ProductId);
        ProductId.setBounds(160, 420, 310, 40);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Product ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 430, 83, 22);

        PPU.setBackground(new java.awt.Color(204, 255, 255));
        PPU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PPU.setForeground(new java.awt.Color(51, 153, 255));
        PPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPUActionPerformed(evt);
            }
        });
        jPanel1.add(PPU);
        PPU.setBounds(160, 480, 310, 40);

        jLabel8.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 255));
        jLabel8.setText("Price Per Unit ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 490, 109, 22);

        ProductName.setBackground(new java.awt.Color(204, 255, 255));
        ProductName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ProductName.setForeground(new java.awt.Color(51, 153, 255));
        ProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductNameActionPerformed(evt);
            }
        });
        jPanel1.add(ProductName);
        ProductName.setBounds(730, 420, 310, 40);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(630, 430, 60, 22);

        Quantity.setBackground(new java.awt.Color(204, 255, 255));
        Quantity.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Quantity.setForeground(new java.awt.Color(51, 153, 255));
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });
        jPanel1.add(Quantity);
        Quantity.setBounds(730, 480, 310, 40);

        jLabel6.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(630, 490, 80, 22);

        AddBut.setBackground(new java.awt.Color(153, 153, 255));
        AddBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        AddBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ADD_But.png"))); // NOI18N
        AddBut.setBorder(null);
        AddBut.setBorderPainted(false);
        AddBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButMouseClicked(evt);
            }
        });
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });
        jPanel1.add(AddBut);
        AddBut.setBounds(110, 540, 140, 40);

        EditBut.setBackground(new java.awt.Color(153, 153, 255));
        EditBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        EditBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit_But.png"))); // NOI18N
        EditBut.setBorder(null);
        EditBut.setBorderPainted(false);
        EditBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditButMouseClicked(evt);
            }
        });
        EditBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButActionPerformed(evt);
            }
        });
        jPanel1.add(EditBut);
        EditBut.setBounds(350, 540, 140, 40);

        DeleteBut.setBackground(new java.awt.Color(153, 153, 255));
        DeleteBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        DeleteBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dlelete_But.png"))); // NOI18N
        DeleteBut.setBorder(null);
        DeleteBut.setBorderPainted(false);
        DeleteBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButMouseClicked(evt);
            }
        });
        DeleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBut);
        DeleteBut.setBounds(600, 540, 140, 40);

        ClearBut.setBackground(new java.awt.Color(153, 153, 255));
        ClearBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ClearBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Clear_1.png"))); // NOI18N
        ClearBut.setBorder(null);
        ClearBut.setBorderPainted(false);
        ClearBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButMouseClicked(evt);
            }
        });
        jPanel1.add(ClearBut);
        ClearBut.setBounds(850, 540, 140, 40);

        LogOut.setBackground(new java.awt.Color(153, 153, 255));
        LogOut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoutBut2.png"))); // NOI18N
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut);
        LogOut.setBounds(910, 70, 180, 40);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackGround(11-6).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButMouseClicked
        new AdminConsol().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButMouseClicked

    private void HomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButActionPerformed

    private void PendingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButActionPerformed

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) ProductTable.getModel();
        int Myindex = ProductTable.getSelectedRow();
        ProductId.setText(model.getValueAt(Myindex, 0).toString());
        ProductName.setText(model.getValueAt(Myindex, 1).toString());
        PPU.setText(model.getValueAt(Myindex, 2).toString());
        Quantity.setText(model.getValueAt(Myindex, 3).toString());
        Category.setSelectedItem(model.getValueAt(Myindex, 4).toString());
    }//GEN-LAST:event_ProductTableMouseClicked

    private void CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoryActionPerformed

    private void PPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPUActionPerformed

    private void ProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductIdActionPerformed

    private void ProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductNameActionPerformed

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    private void AddButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButMouseClicked

        int chk = 0;
        int UniqueChk = 0;
        int value = 10;
        int value2 = 10;
        String Product_Id = "";
        String Product_Name = "";

        if (ProductId.getText().isEmpty() || ProductName.getText().isEmpty() || PPU.getText().isEmpty() || Quantity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information missing");
        } else {
            chk = 1;
            Product_Id = ProductId.getText();
            Product_Name = ProductName.getText();
        }

        if (chk == 1) {

            try {
                con = DriverManager.getConnection(url, uname, pass);

                String Query = "select count(*) from producttable where ProductId = " + Product_Id;
                Statement Add = con.createStatement();
                ResultSet Rs = Add.executeQuery(Query);
                Rs.next();

                value = Rs.getInt("count(*)");
//                    System.out.println(value);
                Add.close();
                con.close();

            } catch (Exception e) {
                e.printStackTrace();
            }

            try {
                con = DriverManager.getConnection(url, uname, pass);

                String Query = "select count(*) from producttable where ProductName = '" + Product_Name + "'";
                Statement Add = con.createStatement();
                ResultSet Rs = Add.executeQuery(Query);
                Rs.next();

                value2 = Rs.getInt("count(*)");
//                    System.out.println(value);
                Add.close();
                con.close();

            } catch (Exception e) {
                e.printStackTrace();
            }

            if (value > 0 || value2 > 0) {
                JOptionPane.showMessageDialog(this, "Product Id or Product Name already existed");
            } else {
                UniqueChk = 1;
            }

        }


          if (UniqueChk == 1) {
            try {
                con = DriverManager.getConnection(url, uname, pass);
                PreparedStatement add = con.prepareStatement("insert into producttable values(?,?,?,?,?)");
                add.setInt(1, Integer.valueOf(ProductId.getText()));
                add.setString(2, ProductName.getText());
                add.setInt(3, Integer.valueOf(PPU.getText()));
                add.setInt(4, Integer.valueOf(Quantity.getText()));
                add.setString(5, Category.getSelectedItem().toString());
                int row = add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Product Added Success");
                con.close();
                SelectProduct();
            } catch (Exception e) {
                e.printStackTrace();
            }
            ProductId.setText("");
            ProductName.setText("");
            PPU.setText("");
            Quantity.setText("");
        }
        
    }//GEN-LAST:event_AddButMouseClicked

    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed

    }//GEN-LAST:event_AddButActionPerformed

    private void EditButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditButMouseClicked
        if (ProductId.getText().isEmpty() || ProductName.getText().isEmpty() || PPU.getText().isEmpty() || Quantity.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information Missing");
        } else {
            try {
                con = DriverManager.getConnection(url, uname, pass);

                String E_ProductId = ProductId.getText();
                String E_ProductName = ProductName.getText();
                String E_PPU = PPU.getText();
                String E_Quantity = Quantity.getText();
                String E_Category = Category.getSelectedItem().toString();

                String Query = "Update shopmanagement.producttable set ProductName='" + E_ProductName + "'" + ",PPU=" + E_PPU + ",Quantity =" + E_Quantity + ",Category='" + E_Category + "'" + "where ProductId=" + E_ProductId + "";
                Statement Add = con.createStatement();
                Add.executeUpdate(Query);
                con.close();
                SelectProduct();
                JOptionPane.showMessageDialog(this, "Product Information Edited Successfully");
            } catch (SQLException e) {
                e.printStackTrace();
            }
            ProductId.setText("");
            ProductName.setText("");
            PPU.setText("");
            Quantity.setText("");
        }
    }//GEN-LAST:event_EditButMouseClicked

    private void DeleteButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButMouseClicked
        if (ProductId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information Missing");
        } else {
            int response = JOptionPane.showConfirmDialog(this, "Do you want to continue the action", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.YES_OPTION) {
                try {
                    con = DriverManager.getConnection(url, uname, pass);
                    String Del_ProductId = ProductId.getText();
                    String Query = "Delete from shopmanagement.producttable where ProductId=" + Del_ProductId;
                    Statement Add = con.createStatement();
                    Add.executeUpdate(Query);
                    con.close();
                    SelectProduct();
                    JOptionPane.showMessageDialog(this, "Product Deleted Successfully");
                } catch (Exception e) {
                    e.printStackTrace();
                }

                ProductId.setText("");
                ProductName.setText("");
                PPU.setText("");
                Quantity.setText("");
            } else {
                ProductId.setText("");
                ProductName.setText("");
                PPU.setText("");
                Quantity.setText("");
            }

        }
    }//GEN-LAST:event_DeleteButMouseClicked

    private void ClearButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButMouseClicked
        ProductId.setText("");
        ProductName.setText("");
        PPU.setText("");
        Quantity.setText("");
    }//GEN-LAST:event_ClearButMouseClicked

    private void DeleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButActionPerformed

    private void EditButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditButActionPerformed

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if( response == JOptionPane.YES_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_CloseButMouseClicked

    private void SellerButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerButMouseClicked
        new SellerBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellerButMouseClicked

    private void ProductButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButMouseClicked
        new ProductBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductButMouseClicked

    private void CategoryButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryButMouseClicked
        new CategoryBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryButMouseClicked

    private void TransactionButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionButMouseClicked
        new Transaction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransactionButMouseClicked

    private void PendingButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingButMouseClicked
        new Pending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PendingButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductBG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JComboBox<String> Category;
    private javax.swing.JButton CategoryBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JLabel CloseBut;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JButton EditBut;
    private javax.swing.JButton HomeBut;
    private javax.swing.JButton LogOut;
    private javax.swing.JTextField PPU;
    private javax.swing.JButton PendingBut;
    private javax.swing.JButton ProductBut;
    private javax.swing.JTextField ProductId;
    private javax.swing.JTextField ProductName;
    private javax.swing.JTable ProductTable;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton SellerBut;
    private javax.swing.JButton TransactionBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
