/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import javax.swing.JOptionPane;

/**
 *
 * @author RashedGtz
 */
public class SellerConsol extends javax.swing.JFrame {

    /**
     * Creates new form SellerConsol
     */
    public SellerConsol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BillingBut = new javax.swing.JButton();
        UpdateProfileBut = new javax.swing.JButton();
        LogOutBut = new javax.swing.JButton();
        CloseBut = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        BillingBut.setBackground(new java.awt.Color(153, 153, 255));
        BillingBut.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        BillingBut.setForeground(new java.awt.Color(255, 255, 255));
        BillingBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BillingPointBut.png"))); // NOI18N
        BillingBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BillingBut.setBorderPainted(false);
        BillingBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BillingBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BillingButMouseClicked(evt);
            }
        });
        BillingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingButActionPerformed(evt);
            }
        });
        jPanel1.add(BillingBut);
        BillingBut.setBounds(220, 190, 240, 220);

        UpdateProfileBut.setBackground(new java.awt.Color(153, 153, 255));
        UpdateProfileBut.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        UpdateProfileBut.setForeground(new java.awt.Color(255, 255, 255));
        UpdateProfileBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UpdateProfile.png"))); // NOI18N
        UpdateProfileBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateProfileBut.setBorderPainted(false);
        UpdateProfileBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        UpdateProfileBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateProfileButMouseClicked(evt);
            }
        });
        UpdateProfileBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateProfileButActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateProfileBut);
        UpdateProfileBut.setBounds(630, 190, 240, 220);

        LogOutBut.setBackground(new java.awt.Color(153, 153, 255));
        LogOutBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        LogOutBut.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoutBut2.png"))); // NOI18N
        LogOutBut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOutBut.setBorderPainted(false);
        LogOutBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LogOutBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButMouseClicked(evt);
            }
        });
        jPanel1.add(LogOutBut);
        LogOutBut.setBounds(950, 70, 130, 40);

        CloseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
        });
        jPanel1.add(CloseBut);
        CloseBut.setBounds(1070, 0, 25, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/SellerConsol.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BillingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillingButActionPerformed

    private void UpdateProfileButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateProfileButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateProfileButActionPerformed

    private void BillingButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BillingButMouseClicked
        new BillingPoint().setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_BillingButMouseClicked

    private void UpdateProfileButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateProfileButMouseClicked
        new SellerProfileUpdate().setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_UpdateProfileButMouseClicked

    private void LogOutButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogOutButMouseClicked

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
         int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if( response == JOptionPane.YES_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_CloseButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerConsol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BillingBut;
    private javax.swing.JLabel CloseBut;
    private javax.swing.JButton LogOutBut;
    private javax.swing.JButton UpdateProfileBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
