/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static shop.management.Login.SellerNameAccepted;

/**
 *
 * @author RashedGtz
 */
public class SellerPasswordUpdate extends javax.swing.JFrame {

    /**
     * Creates new form SellerPasswordUpdate
     */
    public SellerPasswordUpdate() {
        initComponents();
        LoadData();
    }
    
    String url = "jdbc:mysql://localhost:3306/ShopManagement";
    String uname = "root";
    String pass = "239515amimysql";

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;
    
    
    
    String PasswordValue;
    String NewPasswordValue;
    String ConfirmPasswordValue;
    String SellerUserName = new Login().SellerNameAccepted;
    
    public void LoadData() {
        
        UserName.setText(SellerUserName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        CloseBut = new javax.swing.JLabel();
        HomeBut = new javax.swing.JButton();
        CurrentPassword = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        NewPassword = new javax.swing.JPasswordField();
        ShowPassword = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 360));
        setMinimumSize(new java.awt.Dimension(640, 360));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(640, 360));

        jPanel1.setLayout(null);

        UserName.setEditable(false);
        UserName.setBackground(new java.awt.Color(204, 255, 255));
        UserName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(UserName);
        UserName.setBounds(240, 70, 270, 40);

        jLabel13.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("User Name");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(80, 80, 80, 20);

        jLabel12.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("New Password");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(80, 180, 140, 20);

        jLabel11.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("Confirm Password");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 230, 140, 20);

        jLabel14.setFont(new java.awt.Font("Candara", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("Current Password");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(80, 130, 140, 20);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Update Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 20, 190, 31);

        Update.setBackground(new java.awt.Color(153, 153, 255));
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/UpdateBut.png"))); // NOI18N
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(240, 300, 150, 40);

        CloseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
        });
        jPanel1.add(CloseBut);
        CloseBut.setBounds(610, 0, 25, 30);

        HomeBut.setBackground(new java.awt.Color(153, 153, 255));
        HomeBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        HomeBut.setIcon(new javax.swing.ImageIcon("D:\\Icon\\25h\\HOME_BUT.png")); // NOI18N
        HomeBut.setBorder(null);
        HomeBut.setBorderPainted(false);
        HomeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButMouseClicked(evt);
            }
        });
        HomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBut);
        HomeBut.setBounds(10, 20, 50, 40);

        CurrentPassword.setBackground(new java.awt.Color(255, 255, 255));
        CurrentPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        CurrentPassword.setForeground(new java.awt.Color(0, 0, 0));
        CurrentPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CurrentPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(CurrentPassword);
        CurrentPassword.setBounds(240, 120, 270, 40);

        ConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmPassword);
        ConfirmPassword.setBounds(240, 220, 270, 40);

        NewPassword.setBackground(new java.awt.Color(255, 255, 255));
        NewPassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        NewPassword.setForeground(new java.awt.Color(0, 0, 0));
        NewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(NewPassword);
        NewPassword.setBounds(240, 170, 270, 40);

        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ShowPassword);
        ShowPassword.setBounds(240, 270, 150, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PasswordChange.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        
        int oldchk = 0,textchk = 0;
        
        PasswordValue = CurrentPassword.getText();
        NewPasswordValue = NewPassword.getText();
        ConfirmPasswordValue = ConfirmPassword.getText();
        
        if(CurrentPassword.getText().isEmpty() || NewPassword.getText().isEmpty() || ConfirmPassword.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Information Missing!");
        }
        else
        {
            textchk = 1;
        }
        
        //Checking the old Password Start
        if( textchk == 1 )
        {
            String Query = "Select * from shopmanagement.sellerinfo where UserName = '" + UserName.getText() + "' and Password ='" + CurrentPassword.getText() + "'";
            try {
                con = DriverManager.getConnection(url, uname, pass);
                st = con.createStatement();
                rs = st.executeQuery(Query);
                if (rs.next()) {
                    oldchk = 1;
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Current Password");
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        //Checking the old Password End
        
        
        if( oldchk == 1 && textchk == 1)
        {
            if( !NewPasswordValue.equals(ConfirmPasswordValue) )
            {
                JOptionPane.showMessageDialog(this, "Wrong Confirm Password");
            }
            else
            {
                 try {
                con = DriverManager.getConnection(url, uname, pass);

                String E_NewPassword = NewPassword.getText();

                String Query1 = "Update shopmanagement.sellerinfo set Password = '"+E_NewPassword+"'"+" where UserName ='"+SellerUserName+"'";
                Statement Add = con.createStatement();
                Add.executeUpdate(Query1);
                con.close();
                JOptionPane.showMessageDialog(this, "Password Updated Successfully");
            } catch (SQLException e) {
                e.printStackTrace();
            }
            }
        }

        
    }//GEN-LAST:event_UpdateMouseClicked

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if( response == JOptionPane.YES_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_CloseButMouseClicked

    private void HomeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButMouseClicked
        new SellerConsol().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButMouseClicked

    private void HomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButActionPerformed

    private void CurrentPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurrentPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CurrentPasswordActionPerformed

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void NewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordActionPerformed

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        if(ShowPassword.isSelected())
        {
            CurrentPassword.setEchoChar((char)0);
            NewPassword.setEchoChar((char)0);
            ConfirmPassword.setEchoChar((char)0);
        }
        else
        {
            CurrentPassword.setEchoChar('*');
            NewPassword.setEchoChar('*');
            ConfirmPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerPasswordUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerPasswordUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerPasswordUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerPasswordUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerPasswordUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CloseBut;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JPasswordField CurrentPassword;
    private javax.swing.JButton HomeBut;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JCheckBox ShowPassword;
    private javax.swing.JButton Update;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
