/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RashedGtz
 */
public class SellerBG extends javax.swing.JFrame {

    /**
     * Creates new form SellerBG
     */
    public SellerBG() {
        initComponents();
        SelectSeller();
    }

    String url = "jdbc:mysql://localhost:3306/ShopManagement";
    String uname = "root";
    String pass = "239515amimysql";

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    public void SelectSeller() {
        try {
            con = DriverManager.getConnection(url, uname, pass);
            st = con.createStatement();
            rs = st.executeQuery("Select * from shopmanagement.sellerinfo");
            SellerTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        HomeBut = new javax.swing.JButton();
        SellerBut = new javax.swing.JButton();
        ProductBut = new javax.swing.JButton();
        CategoryBut = new javax.swing.JButton();
        TransactionBut = new javax.swing.JButton();
        PendingBut = new javax.swing.JButton();
        CloseBut = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SellerTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        Address = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        FullName = new javax.swing.JTextField();
        UserName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        PhoneNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ClearBut = new javax.swing.JButton();
        DeleteBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(null);

        HomeBut.setBackground(new java.awt.Color(153, 153, 255));
        HomeBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        HomeBut.setIcon(new javax.swing.ImageIcon("D:\\Icon\\25h\\HOME_BUT.png")); // NOI18N
        HomeBut.setBorder(null);
        HomeBut.setBorderPainted(false);
        HomeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButMouseClicked(evt);
            }
        });
        HomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButActionPerformed(evt);
            }
        });
        jPanel2.add(HomeBut);
        HomeBut.setBounds(10, 70, 50, 40);

        SellerBut.setBackground(new java.awt.Color(102, 102, 255));
        SellerBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SellerBut.setForeground(new java.awt.Color(255, 255, 255));
        SellerBut.setText("SELLER");
        SellerBut.setBorder(null);
        SellerBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerButMouseClicked(evt);
            }
        });
        jPanel2.add(SellerBut);
        SellerBut.setBounds(60, 70, 171, 40);

        ProductBut.setBackground(new java.awt.Color(153, 153, 255));
        ProductBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ProductBut.setForeground(new java.awt.Color(255, 255, 255));
        ProductBut.setText("PRODUCT");
        ProductBut.setBorder(null);
        ProductBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButMouseClicked(evt);
            }
        });
        jPanel2.add(ProductBut);
        ProductBut.setBounds(230, 70, 171, 40);

        CategoryBut.setBackground(new java.awt.Color(153, 153, 255));
        CategoryBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        CategoryBut.setForeground(new java.awt.Color(255, 255, 255));
        CategoryBut.setText("CATEGORY");
        CategoryBut.setBorder(null);
        CategoryBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryButMouseClicked(evt);
            }
        });
        jPanel2.add(CategoryBut);
        CategoryBut.setBounds(400, 70, 171, 40);

        TransactionBut.setBackground(new java.awt.Color(153, 153, 255));
        TransactionBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        TransactionBut.setForeground(new java.awt.Color(255, 255, 255));
        TransactionBut.setText("TRANSACTION");
        TransactionBut.setBorder(null);
        TransactionBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionButMouseClicked(evt);
            }
        });
        jPanel2.add(TransactionBut);
        TransactionBut.setBounds(570, 70, 171, 40);

        PendingBut.setBackground(new java.awt.Color(153, 153, 255));
        PendingBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        PendingBut.setForeground(new java.awt.Color(255, 255, 255));
        PendingBut.setText("PENDING");
        PendingBut.setBorder(null);
        PendingBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingButMouseClicked(evt);
            }
        });
        PendingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButActionPerformed(evt);
            }
        });
        jPanel2.add(PendingBut);
        PendingBut.setBounds(740, 70, 171, 40);

        CloseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
        });
        jPanel2.add(CloseBut);
        CloseBut.setBounds(1070, 0, 25, 30);

        SellerTable.setBackground(new java.awt.Color(255, 255, 255));
        SellerTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SellerTable.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        SellerTable.setForeground(new java.awt.Color(153, 153, 153));
        SellerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "User Name", "Full Name", "Address", "Email", "Phone No", "Password", "Gender"
            }
        ));
        SellerTable.setGridColor(new java.awt.Color(204, 204, 204));
        SellerTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        SellerTable.setRowHeight(25);
        SellerTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        SellerTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        SellerTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        SellerTable.setShowGrid(true);
        SellerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(SellerTable);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 170, 1060, 150);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("SELLER LIST");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(470, 130, 160, 30);

        LogOut.setBackground(new java.awt.Color(153, 153, 255));
        LogOut.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoutBut2.png"))); // NOI18N
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel2.add(LogOut);
        LogOut.setBounds(910, 70, 180, 40);

        Address.setEditable(false);
        Address.setBackground(new java.awt.Color(204, 255, 255));
        Address.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(51, 153, 255));
        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        jPanel2.add(Address);
        Address.setBounds(150, 470, 320, 40);

        Gender.setEditable(false);
        Gender.setBackground(new java.awt.Color(204, 255, 255));
        Gender.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Gender.setForeground(new java.awt.Color(51, 153, 255));
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });
        jPanel2.add(Gender);
        Gender.setBounds(750, 470, 320, 40);

        FullName.setEditable(false);
        FullName.setBackground(new java.awt.Color(204, 255, 255));
        FullName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        FullName.setForeground(new java.awt.Color(51, 153, 255));
        FullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameActionPerformed(evt);
            }
        });
        jPanel2.add(FullName);
        FullName.setBounds(150, 410, 320, 40);

        UserName.setEditable(false);
        UserName.setBackground(new java.awt.Color(204, 255, 255));
        UserName.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        UserName.setForeground(new java.awt.Color(51, 153, 255));
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        jPanel2.add(UserName);
        UserName.setBounds(150, 350, 320, 40);

        Email.setEditable(false);
        Email.setBackground(new java.awt.Color(204, 255, 255));
        Email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(51, 153, 255));
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        jPanel2.add(Email);
        Email.setBounds(750, 350, 320, 40);

        PhoneNo.setEditable(false);
        PhoneNo.setBackground(new java.awt.Color(204, 255, 255));
        PhoneNo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        PhoneNo.setForeground(new java.awt.Color(51, 153, 255));
        PhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoActionPerformed(evt);
            }
        });
        jPanel2.add(PhoneNo);
        PhoneNo.setBounds(750, 410, 320, 40);

        jLabel9.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 255));
        jLabel9.setText("Address");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 480, 70, 22);

        jLabel10.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("Phone No");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(650, 420, 80, 22);

        jLabel11.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 255));
        jLabel11.setText("Full Name");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 420, 90, 22);

        jLabel12.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 255));
        jLabel12.setText("User Name");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 360, 90, 22);

        jLabel13.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 255));
        jLabel13.setText("Gender");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(650, 480, 70, 22);

        jLabel14.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 255));
        jLabel14.setText("Email");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(650, 360, 50, 22);

        ClearBut.setBackground(new java.awt.Color(153, 153, 255));
        ClearBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Clear_1.png"))); // NOI18N
        ClearBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButMouseClicked(evt);
            }
        });
        jPanel2.add(ClearBut);
        ClearBut.setBounds(720, 530, 180, 40);

        DeleteBut.setBackground(new java.awt.Color(153, 153, 255));
        DeleteBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Dlelete_But.png"))); // NOI18N
        DeleteBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteButMouseClicked(evt);
            }
        });
        jPanel2.add(DeleteBut);
        DeleteBut.setBounds(230, 535, 180, 40);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackGround(11-6).jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButMouseClicked
        new AdminConsol().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButMouseClicked

    private void HomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButActionPerformed

    private void PendingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButActionPerformed

    private void SellerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) SellerTable.getModel();
        int Myindex = SellerTable.getSelectedRow();
        UserName.setText(model.getValueAt(Myindex, 0).toString());
        FullName.setText(model.getValueAt(Myindex, 1).toString());
        Address.setText(model.getValueAt(Myindex, 2).toString());
        Email.setText(model.getValueAt(Myindex, 3).toString());
        PhoneNo.setText(model.getValueAt(Myindex, 4).toString());
        Gender.setText(model.getValueAt(Myindex, 6).toString());

    }//GEN-LAST:event_SellerTableMouseClicked

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void FullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameActionPerformed

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void PhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoActionPerformed

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if( response == JOptionPane.YES_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_CloseButMouseClicked

    private void DeleteButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteButMouseClicked

        if (UserName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Information Missing");
        } else {
            int response = JOptionPane.showConfirmDialog(this, "Do you want to continue the action", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (response == JOptionPane.YES_OPTION) {
                try {
                    con = DriverManager.getConnection(url, uname, pass);
                    String Del_UserName = UserName.getText();
                    String Query = "Delete from shopmanagement.sellerinfo where UserName = '" + Del_UserName + "'";
                    Statement Add = con.createStatement();
                    Add.executeUpdate(Query);
                    con.close();
                    SelectSeller();
                    JOptionPane.showMessageDialog(this, "Seller Deleted");
                } catch (Exception e) {
                    e.printStackTrace();
                }

                UserName.setText("");
                FullName.setText("");
                Address.setText("");
                Email.setText("");
                PhoneNo.setText("");
                Gender.setText("");
            } else {
                UserName.setText("");
                FullName.setText("");
                Address.setText("");
                Email.setText("");
                PhoneNo.setText("");
                Gender.setText("");

            }

        }

    }//GEN-LAST:event_DeleteButMouseClicked

    private void ClearButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButMouseClicked
        UserName.setText("");
        FullName.setText("");
        Address.setText("");
        Email.setText("");
        PhoneNo.setText("");
        Gender.setText("");
    }//GEN-LAST:event_ClearButMouseClicked

    private void SellerButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerButMouseClicked
        new SellerBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellerButMouseClicked

    private void ProductButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButMouseClicked
        new ProductBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductButMouseClicked

    private void CategoryButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryButMouseClicked
        new CategoryBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryButMouseClicked

    private void TransactionButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionButMouseClicked
        new Transaction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransactionButMouseClicked

    private void PendingButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingButMouseClicked
        new Pending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PendingButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerBG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellerBG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JButton CategoryBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JLabel CloseBut;
    private javax.swing.JButton DeleteBut;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FullName;
    private javax.swing.JTextField Gender;
    private javax.swing.JButton HomeBut;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton PendingBut;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JButton ProductBut;
    private javax.swing.JButton SellerBut;
    private javax.swing.JTable SellerTable;
    private javax.swing.JButton TransactionBut;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
