/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shop.management;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RashedGtz
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form Transaction
     */
    public Transaction() {
        initComponents();
        SelectCategory();
    }

    String url = "jdbc:mysql://localhost:3306/ShopManagement";
    String uname = "root";
    String pass = "239515amimysql";

    Connection con = null;
    Statement st = null;
    ResultSet rs = null;

    public void SelectCategory() {
        try {
            con = DriverManager.getConnection(url, uname, pass);
            st = con.createStatement();
            rs = st.executeQuery("Select * from shopmanagement.transactiontable");
            TransactionTable.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TransactionTable = new javax.swing.JTable();
        Description = new javax.swing.JTextField();
        CustomerName = new javax.swing.JTextField();
        SellerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CloseBut = new javax.swing.JLabel();
        HomeBut = new javax.swing.JButton();
        PendingBut = new javax.swing.JButton();
        ClearBut = new javax.swing.JButton();
        ProductBut = new javax.swing.JButton();
        CategoryBut = new javax.swing.JButton();
        TransactionBut = new javax.swing.JButton();
        Bill_Id = new javax.swing.JTextField();
        LogOut = new javax.swing.JButton();
        SellerBut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        TransactionTable.setBackground(new java.awt.Color(255, 255, 255));
        TransactionTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TransactionTable.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        TransactionTable.setForeground(new java.awt.Color(153, 153, 153));
        TransactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bill Id", "Customer Name", "Seller Name", "Description"
            }
        ));
        TransactionTable.setGridColor(new java.awt.Color(204, 204, 204));
        TransactionTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TransactionTable.setRowHeight(25);
        TransactionTable.setSelectionBackground(new java.awt.Color(102, 204, 255));
        TransactionTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TransactionTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        TransactionTable.setShowGrid(true);
        TransactionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TransactionTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 190, 630, 220);

        Description.setEditable(false);
        Description.setBackground(new java.awt.Color(204, 255, 255));
        Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(Description);
        Description.setBounds(710, 220, 340, 190);

        CustomerName.setEditable(false);
        CustomerName.setBackground(new java.awt.Color(204, 255, 255));
        CustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameActionPerformed(evt);
            }
        });
        jPanel1.add(CustomerName);
        CustomerName.setBounds(140, 530, 250, 40);

        SellerName.setEditable(false);
        SellerName.setBackground(new java.awt.Color(204, 255, 255));
        SellerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SellerNameActionPerformed(evt);
            }
        });
        jPanel1.add(SellerName);
        SellerName.setBounds(710, 460, 250, 40);

        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Bill Id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 470, 44, 22);

        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Seller");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(630, 470, 44, 22);

        jLabel4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Customer");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 540, 76, 22);

        jLabel5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Description");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(830, 190, 89, 22);

        jLabel6.setFont(new java.awt.Font("Candara", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 255));
        jLabel6.setText("Transactions");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 130, 160, 35);

        CloseBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Close_BUT.png"))); // NOI18N
        CloseBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseButMouseClicked(evt);
            }
        });
        jPanel1.add(CloseBut);
        CloseBut.setBounds(1070, 0, 25, 30);

        HomeBut.setBackground(new java.awt.Color(153, 153, 255));
        HomeBut.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        HomeBut.setIcon(new javax.swing.ImageIcon("D:\\Icon\\25h\\HOME_BUT.png")); // NOI18N
        HomeBut.setBorder(null);
        HomeBut.setBorderPainted(false);
        HomeBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButMouseClicked(evt);
            }
        });
        HomeBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButActionPerformed(evt);
            }
        });
        jPanel1.add(HomeBut);
        HomeBut.setBounds(10, 70, 50, 40);

        PendingBut.setBackground(new java.awt.Color(153, 153, 255));
        PendingBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        PendingBut.setForeground(new java.awt.Color(255, 255, 255));
        PendingBut.setText("PENDING");
        PendingBut.setBorder(null);
        PendingBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PendingButMouseClicked(evt);
            }
        });
        PendingBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PendingButActionPerformed(evt);
            }
        });
        jPanel1.add(PendingBut);
        PendingBut.setBounds(740, 70, 171, 40);

        ClearBut.setBackground(new java.awt.Color(153, 153, 255));
        ClearBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ClearBut.setForeground(new java.awt.Color(255, 255, 255));
        ClearBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Clear_1.png"))); // NOI18N
        ClearBut.setBorder(null);
        ClearBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearButMouseClicked(evt);
            }
        });
        jPanel1.add(ClearBut);
        ClearBut.setBounds(760, 530, 171, 40);

        ProductBut.setBackground(new java.awt.Color(153, 153, 255));
        ProductBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ProductBut.setForeground(new java.awt.Color(255, 255, 255));
        ProductBut.setText("PRODUCT");
        ProductBut.setBorder(null);
        ProductBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductButMouseClicked(evt);
            }
        });
        jPanel1.add(ProductBut);
        ProductBut.setBounds(230, 70, 171, 40);

        CategoryBut.setBackground(new java.awt.Color(153, 153, 255));
        CategoryBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        CategoryBut.setForeground(new java.awt.Color(255, 255, 255));
        CategoryBut.setText("CATEGORY");
        CategoryBut.setBorder(null);
        CategoryBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryButMouseClicked(evt);
            }
        });
        jPanel1.add(CategoryBut);
        CategoryBut.setBounds(400, 70, 171, 40);

        TransactionBut.setBackground(new java.awt.Color(102, 102, 255));
        TransactionBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        TransactionBut.setForeground(new java.awt.Color(255, 255, 255));
        TransactionBut.setText("TRANSACTION");
        TransactionBut.setBorder(null);
        TransactionBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransactionButMouseClicked(evt);
            }
        });
        jPanel1.add(TransactionBut);
        TransactionBut.setBounds(570, 70, 171, 40);

        Bill_Id.setEditable(false);
        Bill_Id.setBackground(new java.awt.Color(204, 255, 255));
        Bill_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bill_IdActionPerformed(evt);
            }
        });
        jPanel1.add(Bill_Id);
        Bill_Id.setBounds(140, 460, 250, 40);

        LogOut.setBackground(new java.awt.Color(153, 153, 255));
        LogOut.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 255, 255));
        LogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoutBut2.png"))); // NOI18N
        LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogOut.setBorderPainted(false);
        LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutMouseClicked(evt);
            }
        });
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut);
        LogOut.setBounds(910, 70, 180, 40);

        SellerBut.setBackground(new java.awt.Color(153, 153, 255));
        SellerBut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SellerBut.setForeground(new java.awt.Color(255, 255, 255));
        SellerBut.setText("SELLER");
        SellerBut.setBorder(null);
        SellerBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SellerButMouseClicked(evt);
            }
        });
        jPanel1.add(SellerBut);
        SellerBut.setBounds(60, 70, 171, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BackGround(11-6).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1100, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButMouseClicked
        new AdminConsol().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButMouseClicked

    private void PendingButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PendingButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PendingButActionPerformed

    private void HomeButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButActionPerformed

    private void SellerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SellerNameActionPerformed

    private void CustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameActionPerformed

    private void DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionActionPerformed

    private void TransactionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionTableMouseClicked

        DefaultTableModel model = (DefaultTableModel) TransactionTable.getModel();
        int Myindex = TransactionTable.getSelectedRow();
        Bill_Id.setText(model.getValueAt(Myindex, 0).toString());
        CustomerName.setText(model.getValueAt(Myindex, 1).toString());
        SellerName.setText(model.getValueAt(Myindex, 2).toString());
        Description.setText(model.getValueAt(Myindex, 3).toString());
    }//GEN-LAST:event_TransactionTableMouseClicked

    private void Bill_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bill_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bill_IdActionPerformed

    private void LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutMouseClicked
       int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            new Login().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_LogOutMouseClicked

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogOutActionPerformed

    private void CloseButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseButMouseClicked
       int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            
            if( response == JOptionPane.YES_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_CloseButMouseClicked

    private void ClearButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButMouseClicked
        Bill_Id.setText("");
        CustomerName.setText("");
        SellerName.setText("");
        Description.setText("");
    }//GEN-LAST:event_ClearButMouseClicked

    private void SellerButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SellerButMouseClicked
        new SellerBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SellerButMouseClicked

    private void ProductButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductButMouseClicked
        new ProductBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductButMouseClicked

    private void CategoryButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryButMouseClicked
        new CategoryBG().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CategoryButMouseClicked

    private void PendingButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PendingButMouseClicked
        new Pending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PendingButMouseClicked

    private void TransactionButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransactionButMouseClicked
        new Transaction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TransactionButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bill_Id;
    private javax.swing.JButton CategoryBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JLabel CloseBut;
    private javax.swing.JTextField CustomerName;
    private javax.swing.JTextField Description;
    private javax.swing.JButton HomeBut;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton PendingBut;
    private javax.swing.JButton ProductBut;
    private javax.swing.JButton SellerBut;
    private javax.swing.JTextField SellerName;
    private javax.swing.JButton TransactionBut;
    private javax.swing.JTable TransactionTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
